Add dependency upgrade task to release-action
Signed-off-by: Michael Telatynski <7t3chguy@gmail.com>

diff --git a/.github/workflows/release-action.yml b/.github/workflows/release-action.yml
--- a/.github/workflows/release-action.yml
+++ b/.github/workflows/release-action.yml
@@ -14,6 +14,14 @@ on:
                 description: Publish to npm
                 type: boolean
                 default: false
+            dependencies:
+                description: |
+                    List of dependencies to update in `npm-dep=version` format.
+                    `version` can be `"current"` to leave it at the current version,
+                    `version` can be `"latest"` where it'll require an update to occur,
+                    if combined with `final` will require the update to be to a non-rc version.
+                type: string
+                required: false
 concurrency: ${{ github.workflow }}
 jobs:
     release:
@@ -55,6 +63,54 @@ jobs:
 
             - name: Install dependencies
               run: "yarn install --frozen-lockfile"
+
+            - name: Update dependencies
+              if: inputs.dependencies
+              run: |
+                  while IFS= read -r DEPENDENCY; do
+                      IFS="=" read -r PACKAGE UPDATE_VERSION <<< "$DEPENDENCY"
+                      if [ "$UPDATE_VERSION" == "current" ]
+                      then
+                          echo "Not updating dependency $PACKAGE"
+                          continue
+                      fi
+
+                      local CURRENT_VERSION=$(cat package.json | jq -r .dependencies[\"$PACKAGE\"])
+                      if [ "$CURRENT_VERSION" == "null" ]
+                      then
+                          echo "Unable to find $PACKAGE in package.json"
+                          exit 1
+                      fi
+                      echo "Current $PACKAGE version is $CURRENT_VERSION"
+
+                      if [ "$UPDATE_VERSION" == "latest" ]
+                      then
+                          echo "Checking latest version of $PACKAGE..."
+                          local UPDATE_VERSION=$(yarn info -s "$PACKAGE" dist-tags.next)
+                          if [ "$CURRENT_VERSION" == "$UPDATE_VERSION" ]
+                          then
+                              echo "No update available for $PACKAGE"
+                              exit 1
+                          fi
+
+                          [[ "$UPDATE_VERSION" == *"-rc."* ]]; IS_RC=$?
+                          if [[ "$IS_RC" != "$FINAL" ]]
+                          then
+                              [[ "$FINAL" == "1" ]] && KIND="FINAL" || KIND="NON-FINAL"
+                              echo "Rejecting update to $UPDATE_VERSION for a $KIND release"
+                              echo "If it was intentional then specify the version explicitly"
+                              exit 1
+                          fi
+                      fi
+
+                      echo "Upgrading $PACKAGE to $UPDATE_VERSION..."
+                      yarn add -E "$PACKAGE@$UPDATE_VERSION"
+                      git add -u
+                      git commit -m "Upgrade $PACKAGE to $UPDATE_VERSION"
+                  done <<< "$DEPENDENCIES"
+              env:
+                  DEPENDENCIES: ${{ inputs.dependencies }}
+                  FINAL: ${{ inputs.final }}
 
             - name: Bump package.json version
               run: yarn version --no-git-tag-version --new-version "$VERSION"
