Additional check to ensure artifacts are downloaded
Signed-off-by: Michael Telatynski <7t3chguy@gmail.com>

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -44,6 +44,7 @@ jobs:
 
             - name: 📥 Download artifact
               uses: actions/download-artifact@v4
+              id: download
               if: ${{ !inputs.sharded }}
               with:
                   github-token: ${{ secrets.GITHUB_TOKEN }}
@@ -52,6 +53,7 @@ jobs:
                   path: coverage
             - name: 📥 Download sharded artifacts
               uses: actions/download-artifact@v4
+              id: download
               if: inputs.sharded
               with:
                   github-token: ${{ secrets.GITHUB_TOKEN }}
@@ -59,6 +61,11 @@ jobs:
                   pattern: coverage-*
                   path: coverage
                   merge-multiple: true
+            - name: Fail if failed to download files
+              if: steps.download.outputs.download-path == ''
+              run: |
+                  echo "Failed to download coverage artifact"
+                  exit 1
 
             - id: extra_args
               run: |
